Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/NotificheController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using PortaleRegione.Client.Helpers;
using PortaleRegione.DTO.Domain;
using PortaleRegione.DTO.Enum;
using PortaleRegione.DTO.Response;
using PortaleRegione.Gateway;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller notifiche
    /// </summary>
    [Authorize]
    [RoutePrefix("notifiche")]
    public class NotificheController : BaseController
    {
        public ActionResult RiepilogoNotifiche(bool is_inviate)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        [Route("view")]
        public async Task<ActionResult> RiepilogoNotifiche(bool is_inviate, bool archivio, int page = 1, int size = 50)
        {
            BaseResponse<NotificaDto> model;
            if (!is_inviate)
                model = await ApiGateway.GetNotificheRicevute(page, size, archivio);
            else
                model = await ApiGateway.GetNotificheInviate(page, size, archivio);

            return View("RiepilogoNotifiche", model);
        }

        [HttpGet]
        [Route("{id:int}/destinatari")]
        public async Task<ActionResult> GetDestinatariNotifica(int id)
        {
            var destinatari = await ApiGateway.GetDestinatariNotifica(id);
            var result = await Utility.GetDestinatariNotifica(destinatari);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Route("destinatari")]
        public async Task<ActionResult> GetListaDestinatari(Guid atto, TipoDestinatarioNotificaEnum tipo)
        {
            var destinatari = await ApiGateway.GetListaDestinatari(atto, tipo);
            return Json(destinatari, JsonRequestBehavior.AllowGet);
        }
    }
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/PersoneController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using PortaleRegione.DTO.Enum;
using PortaleRegione.DTO.Model;
using PortaleRegione.DTO.Response;
using PortaleRegione.Gateway;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller persone
    /// </summary>
    [Authorize]
    [RoutePrefix("persone")]
    public class PersoneController : BaseController
    {
        [Route("{id:guid}")]
        public async Task<ActionResult> GetPersona(Guid id)
        {
            return Json(await ApiGateway.GetPersona(id), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = RuoliEnum.Amministratore_PEM + "," + RuoliEnum.Segreteria_Assemblea)]
        [HttpGet]
        [Route("all")]
        public async Task<ActionResult> GetPersone()
        {
            return Json(await ApiGateway.GetPersone(), JsonRequestBehavior.AllowGet);
        }

        [Route("cambio-pin")]
        public async Task<ActionResult> CambioPin()
        {
            return View("CambioPinForm", new CambioPinModel());
        }

        [Route("conferma-cambio-pin")]
        [HttpPost]
        public async Task<ActionResult> SalvaPin(CambioPinModel model)
        {
            try
            {
                await ApiGateway.SalvaPin(model);
                return Json(Url.Action("RiepilogoSedute", "Sedute"), JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return Json(new ErrorResponse {message = e.Message}, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Controllers/VideoTutorialController.cs
/*
 * Copyright (C) 2019 Consiglio Regionale della Lombardia
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

using System.Web.Mvc;

namespace PortaleRegione.Client.Controllers
{
    /// <summary>
    ///     Controller video
    /// </summary>
    [Authorize]
    [RoutePrefix("emendamenti")]
    public class VideoTutorialController : BaseController
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }
    }
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Shared/_Layout.cshtml
@using System.Configuration
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Applicazione ASP.NET</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    @Styles.Render("~/Content/css")
    <script src="https://cdn.tiny.cloud/1/2mqsotaemo0a1w4fsiq3j7vf4901zkryk9pem18pws7m6do9/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/logic")

    <script>
        baseUrl = '@Html.Raw(ConfigurationManager.AppSettings["URL_CLIENT"])';
        AggiornaPosizioneTemi(baseUrl)
        var cssTheme = "";
        var mode = getClientMode();
        if (mode == 2) {
            cssTheme = trattazione_theme;
        } else {
            cssTheme = gruppi_theme;
        }

        var cssId = 'client-mode-theme'; // you could encode the css path itself to generate id..
        if (!document.getElementById(cssId)) {
            var head = document.getElementsByTagName('head')[0];
            var link = document.createElement('link');
            link.id = cssId;
            link.rel = 'stylesheet';
            link.type = 'text/css';
            link.href = cssTheme;
            link.media = 'all';
            head.appendChild(link);
        }
    </script>
</head>
<body>

@Html.Partial("_NavigationBar")

<main>
    @Html.Partial("_SXNavigationBar")
    @RenderBody()
</main>


<div id="modalAction" class="modal">
    <div class="modal-content">
        <h5 id="emActionDisplayName"></h5>
        <p id="emActionMessage"></p>
        <div class="modal-footer">
            <button type="button" class="btn modal-close grey">Annulla</button>
            <a id="btnConfermaAction" class="btn red" href="#">Elimina</a>
        </div>
    </div>
</div>

@RenderSection("scripts", false)

<script>
    $("body").on("keyup",
        function(event) {
            // Cancel the default action, if needed
            event.preventDefault();
            // Number 13 is the "Enter" key on the keyboard
            if (event.keyCode === 27) {
                // Trigger the button element with a click
                swal({
                        title: "Ops!",
                        text: "Hai premuto il tasto 'ESC'. Vuoi uscire dal portale?",
                        icon: "warning",
                        buttons: { cancel: "Annulla", confirm: "Esci" },
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (!willDelete) return;
                        logout();
                    });
            }
        });
</script>
</body>
</html>

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Shared/_NavigationBar.cshtml
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper">
            <a href="#" data-target="slide-out" class="sidenav-trigger show-on-small">
                <i class="material-icons">menu</i>
            </a>
            <a asp-area="" asp-controller="Sedute" asp-action="RiepilogoSedute" class="brand-logo">
                <img src="https://pem.consiglio.regione.lombardia.it/images/logo.png" width="22" alt="" loading="lazy">
                <span class="hide-on-small-only black-text" style="font-weight: lighter;">Portale Regione - Presentazione emendamenti</span>
            </a>
        </div>
        <div class="nav-content">
            <a id="btnSearch" class="btn-floating btn-large halfway-fab waves-effect waves-light green darken-3" onclick="openSearch();">
                <i class="material-icons">more_vert</i>
            </a>
        </div>
    </nav>
</div>

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Shared/_PaginationBar.cshtml
@model PortaleRegione.DTO.Response.Paging

@{
    var sizeArray = new[] {20, 50, 100, 250};

    //Emendamenti
    var view = HttpUtility.ParseQueryString(Request.Url.Query).Get("view");
    var limite = HttpUtility.ParseQueryString(Request.Url.Query).Get("size");
    var mode = HttpUtility.ParseQueryString(Request.Url.Query).Get("mode");
    if (string.IsNullOrEmpty(mode))
    {
        mode = "1";
    }
    //Notifiche
    var archivio = HttpUtility.ParseQueryString(Request.Url.Query).Get("archivio");
    var is_inviate = HttpUtility.ParseQueryString(Request.Url.Query).Get("is_inviate");

    if (string.IsNullOrEmpty(limite))
    {
        limite = Model.Limit.ToString();
    }

    var port = "";
    if (Request.Url.Port > 0)
    {
        port = string.Format(":{0}", Request.Url.Port);
    }

    var url = string.Format("{0}://{1}{2}{3}", Request.Url.Scheme, Request.Url.Host, port, Request.Url.AbsolutePath);

    var prev_class_style = Model.Has_Prev ? "waves-effect" : "disabled";
    var next_class_style = Model.Has_Next ? "waves-effect" : "disabled";

    var prev_url = Model.Has_Prev ? string.Format("{0}{1}", url, Model.Prev_Url.Query) : "#!";
    var next_url = Model.Has_Next ? string.Format("{0}{1}", url, Model.Next_Url.Query) : "#!";

    if (!string.IsNullOrEmpty(view))
    {
        prev_url += string.Format("&view={0}", view);
        next_url += string.Format("&view={0}", view);
    }
    if (!string.IsNullOrEmpty(archivio))
    {
        prev_url += string.Format("&archivio={0}", archivio);
        next_url += string.Format("&archivio={0}", archivio);
    }
    if (!string.IsNullOrEmpty(is_inviate))
    {
        prev_url += string.Format("&is_inviate={0}", is_inviate);
        next_url += string.Format("&is_inviate={0}", is_inviate);
    }
    if (!string.IsNullOrEmpty(mode))
    {
        prev_url += string.Format("&mode={0}", mode);
        next_url += string.Format("&mode={0}", mode);
    }

        <div class="row valign-wrapper">
            <div class="col l6 m6 s12">
                <ul class="pagination">
                    @if (Model.Has_Prev)
                    {
                        <li class="@prev_class_style" style="margin-top: -4px;">
                            <a href="@prev_url">
                                <i class="material-icons">chevron_left</i>
                            </a>
                        </li>
                    }
                    @if (Model.Last_Page > 1)
                    {
                        <li class="waves-effect">
                            <span class="badge">Pagina @Model.Page di @Model.Last_Page</span>
                        </li>
                    }
                    
                    @if (Model.Has_Next)
                    {
                        <li class="@next_class_style" style="margin-top: -4px;">
                            <a href="@next_url">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </li>
                    }

                    <li>
                        <div class="chip deep-purple lighten-5" style="margin-top: -5px;">@Model.Total documenti trovati</div>
                        <input id="hdTotaleDocumenti" type="hidden" value="@Model.Total"/>
                    </li>
                </ul>
            </div>
            <div class="col l6 m6 s12 right-align" style="margin-top: -5px;">
                <div class="chip deep-purple lighten-5 center" style="min-width: unset">
                    Paginazione
                    <a class='dropdown-trigger chip grey white-text' href='#' data-target='ddlPaginazione' style="font-size: small; margin-right: -12px; min-width: unset">@limite</a>
                    <ul id='ddlPaginazione' class='dropdown-content'>
                        @for (var i = 0; i < sizeArray.Length; i++)
                        {
                            var sized_url = string.Format("{0}?size={1}", url, sizeArray[i]);
                            <li>
                                <a href=@sized_url>@sizeArray[i]</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
}

Sorgenti Client/PortaleRegione.Client/PortaleRegione.Client/Views/Shared/_SXNavigationBar.cshtml
@using Newtonsoft.Json
@using PortaleRegione.DTO.Domain
@using PortaleRegione.DTO.Enum
@using PortaleRegione.DTO.Model
@{
    var displayName = "";
    var foto = "";
    IEnumerable<RuoliDto> ruoli = new List<RuoliDto>();
    IEnumerable<KeyValueDto> gruppiAdmin = new List<KeyValueDto>();
    GruppiDto gruppo = null;
    var currentRole = RuoliIntEnum.Utente;
    var carica = string.Empty;

    if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        var authCookie1 = Request.Cookies["PRCookies1"];
        var authCookie2 = Request.Cookies["PRCookies2"];
        var authCookie3 = Request.Cookies["PRCookies3"];
        if (authCookie1 != null && authCookie2 != null && authCookie3 != null)
        {
            if (!string.IsNullOrEmpty(authCookie1.Value) && !string.IsNullOrEmpty(authCookie2.Value) && !string.IsNullOrEmpty(authCookie3.Value))
            {
                var authenticationTicket1 = FormsAuthentication.Decrypt(authCookie1.Value);
                var authenticationTicket2 = FormsAuthentication.Decrypt(authCookie2.Value);
                var authenticationTicket3 = FormsAuthentication.Decrypt(authCookie3.Value);
                var data = JsonConvert.DeserializeObject<PersonaDto>(string.Format("{0}{1}{2}", authenticationTicket1.UserData, authenticationTicket2.UserData, authenticationTicket3.UserData));

                currentRole = data.CurrentRole;
                ruoli = data.Ruoli;
                displayName = data.DisplayName;
                foto = data.foto;
                gruppo = data.Gruppo;
                carica = data.IsGiunta() ? data.Carica : string.Empty;
                if (HttpContext.Current.User.IsInRole(RuoliEnum.Amministratore_PEM))
                {
                    var gCookie = Request.Cookies["GCookies"];
                    if (gCookie != null)
                    {
                        if (!string.IsNullOrEmpty(gCookie.Value))
                        {
                            var gTicket = FormsAuthentication.Decrypt(gCookie.Value);
                            var gData = JsonConvert.DeserializeObject<IEnumerable<KeyValueDto>>(gTicket.UserData);
                            if (gData != null)
                            {
                                gruppiAdmin = gData;
                            }
                        }
                    }
                }
            }
        }
    }
}

<div id="slide-out" class="sidenav sidenav-fixed">
    @if (!string.IsNullOrEmpty(carica))
    {
        <div class="row green darken-3 center" style="margin: 0 !important">
            <div class="col s12">
                <label class="white-text" style="padding: 10px">@carica</label>
            </div>
        </div>
    }
    <ul style="margin: 0">
        <li>
            <div class="user-view" style="padding: 10px">
                <div class="row" style="margin-bottom: unset !important;margin-top: unset !important">
                    <div class="col s12">
                        <ul class="dropdown-content" id="ddlSubMenu" style="z-index: 9999">
                            <li>
                                <a href="@Url.Action("CambioPin", "Persone")">
                                    <i class="material-icons">settings</i>Impostazioni Pin
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Index", "VideoTutorial")">
                                    <i class="material-icons">music_video</i>Video Tutorial
                                </a>
                            </li>
                        </ul>
                        <a class="dropdown-trigger waves-effect black-text" data-target="ddlSubMenu" style="margin-top: 4px">
                            <i class="material-icons">more_vert</i>
                        </a>
                    </div>
                </div>
                    <div class="row valign-wrapper" style="margin-bottom: unset !important;margin-top: unset !important">
                        <div class="col s3 center">
                            <img class="responsive-img circle" style="width: 35px;height: 35px" src='http://intranet.consiglio.regione.lombardia.it/GC/foto/@foto'>
                        </div>
                        <div class="col s9" style="padding-left: 0">
                            <h6 class="black-text">
                                <b>@displayName</b>
                            </h6>
                        </div>
                    </div>
                <div class="row">
                    <div class="col s12">
                        @if (ruoli.Any())
                        {
                            var testo = string.Empty;
                            var ruoliDto = ruoli.SingleOrDefault(r => r.IDruolo == (int) currentRole);

                            if (ruoliDto != null)
                            {
                                testo = ruoliDto.Ruolo;
                            }
                            else
                            {
                                testo = "Responsabile Segreteria Politica";
                            }

                            var triggerClass = "";
                            var iconClassSwapRuoli = "";
                            if (ruoli.Count() > 1)
                            {
                                //Aggiungo la classe solo se ho un drop down da aprire, altrimenti materialize va in errore
                                triggerClass = "dropdown-trigger";
                                iconClassSwapRuoli = "<i class='material-icons tiny'>swap_horiz</i>";
                                <ul id='ddlCambioRuolo' class='dropdown-content'>
                                    @foreach (var ruolo in ruoli)
                                    {
                                        if (ruolo.IDruolo != (int) currentRole)
                                        {
                                            <li>
                                                <a style="overflow: hidden; text-overflow: ellipsis;" href="@Url.Action("CambioRuolo", "Autenticazione", new {ruolo = ruolo.IDruolo, returnUrl = Request.Url})">@ruolo.Ruolo</a>
                                            </li>
                                        }
                                    }
                                </ul>
                            }

                            <a class='@triggerClass truncate chip black-text' style="min-width: unset; background-color: unset" href='#' data-target='ddlCambioRuolo'>
                                @testo @Html.Raw(iconClassSwapRuoli)
                            </a>
                        }
                    </div>
                    <div class="col s12" style="margin-top:-15px">
                        @{
                            var testoGruppo = gruppo == null ? "Sconosciuto" : gruppo.codice_gruppo;
                            if (HttpContext.Current.User.IsInRole(RuoliEnum.Assessore_Sottosegretario_Giunta)
                                || HttpContext.Current.User.IsInRole(RuoliEnum.Responsabile_Segreteria_Giunta)
                                || HttpContext.Current.User.IsInRole(RuoliEnum.Segreteria_Giunta_Regionale)
                                || HttpContext.Current.User.IsInRole(RuoliEnum.Amministratore_Giunta))
                            {
                                testoGruppo = "Giunta";
                            }
                            var triggerClassGruppi = "";
                            var iconClassSwapGruppi = "";
                            if (gruppiAdmin.Any())
                            {
                                triggerClassGruppi = "dropdown-trigger";
                                iconClassSwapGruppi = "<i class='material-icons tiny'>swap_horiz</i>";
                                <ul id='ddlCambioGruppo' class='dropdown-content'>
                                    @foreach (var gruppiDto in gruppiAdmin)
                                    {
                                        <li>
                                            <a class="truncate" style="height: unset !important; padding: 0 20px 0 20px !important;"
                                               href="@Url.Action("CambioGruppo", "Autenticazione", new {gruppo = gruppiDto.id, returnUrl = Request.Url})">
                                                <label class="active">(@gruppiDto.sigla)</label> @gruppiDto.descr
                                            </a>
                                        </li>
                                    }
                                </ul>
                            }

                            if (!HttpContext.Current.User.IsInRole(RuoliEnum.Segreteria_Assemblea))
                            {
                                <a class='@triggerClassGruppi chip truncate black-text' style="min-width: unset; background-color: unset" href='#' data-target='ddlCambioGruppo'>
                                    @testoGruppo @Html.Raw(iconClassSwapGruppi)
                                </a>
                            }
                        }
                    </div>
                </div>
            </div>
        </li>
        <li>
            <a class="waves-effect" href="@Url.Action("RiepilogoSedute", "Sedute")"><i class="material-icons">event</i>Riepilogo sedute</a>
        </li>
        <li>
            <a class="waves-effect" onclick="AbilitaTrattazione('@Request.RawUrl')"><i class="material-icons">airplay</i>Trattazione aula</a>
        </li>
        <li>
            <a class="waves-effect" href="@Url.Action("RiepilogoNotifiche", "Notifiche", new {is_inviate = false, archivio = false})"><i class="material-icons">email</i>Notifiche</a>
        </li>
        <li>
            <a class="waves-effect" href="@Url.Action("Index", "Stampe")"><i class="material-icons">print</i>Gestione stampe</a>
        </li>
        @if (currentRole == RuoliIntEnum.Amministratore_PEM)
        {
            <li>
                <a class="waves-effect" href="@Url.Action("RiepilogoUtenti", "AdminPanel")"><i class="material-icons">build</i>Amministrazione</a>
            </li>
        }
    </ul>
    <div class="fixed-action-btn" style="bottom: 150px !important; left: 23px; right: unset !important;">
        @using (Html.BeginForm("Logout", "Autenticazione", FormMethod.Post, new {id = "formLogout"}))
        {
            @Html.AntiForgeryToken()
            <a class="chip hoverable red center white-text" onclick="logout()" style="width: 255px;">
                <i class="icon material-icons">lock_outline</i> Esci
            </a>
        }

        <script>
            function logout() {
                $('#formLogout').submit();
            }
        </script>
    </div>
</div>